# Generated by Django 3.2.15 on 2022-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
