from django.urls import path
from reader.views import TeacherFilteredListView, reader_list

app_name = 'readers'

urlpatterns = [
    # This view uses a filterView (Similar to modelView - all autogenerated)
    path('readers', TeacherFilteredListView.as_view()),
    # This view uses a filterSet (you specify your fields to filter from
    path('readersV2', reader_list),
]