# Generated by Django 3.2.15 on 2022-08-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='language',
            field=models.TextField(choices=[('EN', 'ENGLISH'), ('SP', 'SP'), ('FR', 'FRENCH')], null=True),
        ),
    ]
