# Generated by Django 3.2.15 on 2022-08-28 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_reader_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='reader',
            name='language',
            field=models.TextField(choices=[('EN', 'ENGLISH'), ('SP', 'SPANISH'), ('FR', 'FRENCH')], null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reader.company'),
        ),
    ]
